# Generated by Django 2.1.5 on 2019-01-06 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogMongo', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
